require: rubocop-rspec

Lint/UselessAssignment:
  Exclude:
    - "spec/spec_helper.rb"

Metrics/LineLength:
  Exclude:
    - "*.gemspec"

Style/MultilineOperationIndentation:
  Exclude:
    - "lib/versio_rac1/podcast/episode.rb"
